#spring.datasource.url: jdbc:h2:file:./camunda-h2-database
#
#camunda.bpm.admin-user:
#  id: admin
#  password: admin
#
## https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/
## https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/configuration/

spring:
  mail:
    host: "smtp.gmail.com"
    port: "587"
    username: "michalpl6188@gmail.com"
    password: "awxltchswededsrs"
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://195.150.230.208:5432/2023_polak_michal?currentSchema=ticket_booking
    username: 2023_polak_michal
    password: 35229
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false # Only for delete warning

camunda:
  client:
    mode: saas
    auth:
      client-id: Ci~mKD6hAKrryws1cyHkIndQV2kgZ_RX
      client-secret: srdrNn_7MVX7I5Qeyt.kXJti-.4iIHhOM6JIW7fuOpT9X-kEZ.GEUGo94eeoNjMi
    cluster-id: 84eaee38-4bb9-4ed7-b5dc-4395bc8bb99f
    region: bru-2



#  bpm:
#    enforce-ttl: true
#    default-history-time-to-live: 30


#zeebe:
#  client:
#    cloud:
#      clusterId: 84eaee38-4bb9-4ed7-b5dc-4395bc8bb99f
#      clientId: Ci~mKD6hAKrryws1cyHkIndQV2kgZ_RX
#      clientSecret: srdrNn_7MVX7I5Qeyt.kXJti-.4iIHhOM6JIW7fuOpT9X-kEZ.GEUGo94eeoNjMi
#    gatewayAddress: "localhost:26500" # Lokalny broker (dla self-managed)
#    security:
#      plaintext: true
